# Generated by Django 5.2.5 on 2025-08-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_follow_delete_userfollower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
